/**
  ******************************************************************************
  * @file           : geofence.h
  * @brief          : Algorithms for geofencing
  ******************************************************************************
  * Imperial College Space Society
	* Medad Newman, Richard Ibbotson
	* Modified from TT7's code 
	* https://github.com/TomasTT7/TT7F-Float-Tracker
  * The following coordinates are autogenerated from a kml file containing all the polygons.
  *
  ******************************************************************************
  */

#ifdef __cplusplus
extern "C"
{
#endif

#ifndef GEOFENCE_H
#define GEOFENCE_H

	/* ==================================================================== */
	/* ========================== include files =========================== */
	/* ==================================================================== */

	/* Inclusion of system and local header files goes here */

#include "stdint.h"
#include "LoRaMac.h"

	/* ==================================================================== */
	/* ============================ constants ============================= */
	/* ==================================================================== */

	/* #define and enum statements go here */

	/* ==================================================================== */
	/* ========================== public data ============================= */
	/* ==================================================================== */

	/* Definition of public (external) data types go here */

	typedef enum
	{
		TX_OK = 0,
		TX_NOT_OK
	} tx_permission_t;

	typedef struct
	{
		LoRaMacRegion_t current_loramac_region;
		tx_permission_t tx_permission;

	} geofence_status_t;

	/* ==================================================================== */
	/* ======================= public functions =========================== */
	/* ==================================================================== */

	/* Function prototypes for public (external) functions go here */

	void update_geofence_position(float latitude, float longitude);
	void geofence_init(void);
	LoRaMacRegion_t get_current_loramac_region();
	void set_current_loramac_region(LoRaMacRegion_t region);
	tx_permission_t get_current_tx_permission();


#endif
#ifdef __cplusplus
}
#endif
