name: CMake Build

on:
  push:
    branches: ["icspace-dev"]
  pull_request:
    branches: ["icspace-dev"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Toolchain
        run: sudo apt-get -y install gcc-arm-none-eabi

      - name: Configure CMake
        run: cmake --preset on_target_configs

      - name: Build
        run: cmake --build --preset target_build

